# CIFAR-10展示配置
# 用于CIFAR-10数据集的训练展示

# 超参数配置
hyperparameters:
  learning_rate: 0.001
  batch_size: 128
  epochs: 10
  dropout: 0.1

# 训练配置
training:
  experiment_name: "cifar10_demo"
  save_model: true
  model_save_path: "models/cifar10_model.pth"

# SwanLab配置
swanlab:
  project_name: "cifar10_training"
  description: "CIFAR-10图像分类训练展示"

# 数据配置
data:
  type: "cifar10"
  root: "./data"
  download: true
  augment: true
  num_workers: 4

# GPU配置
gpu:
  device_ids: "2,3"
  auto_select: true

# 模型配置
model:
  type: "resnet18"  # 使用预训练ResNet18
  params:
    freeze_backbone: false

# 损失函数配置
loss:
  type: "cross_entropy"
  params: {}

# 优化器配置
optimizer:
  type: "adam"
  params:
    weight_decay: 0

# 学习率调度器配置
scheduler:
  type: "onecycle"
  params:
    step_size: 10
    gamma: 0.1