# 统一配置文件
# 支持单次训练和网格搜索的通用配置

# 超参数配置
hyperparameters:
  learning_rate: 0.001
  batch_size: 256
  epochs: 3
  dropout: 0.1

# 训练配置
training:
  experiment_name: "default_exp"
  save_model: true
  model_save_path: "models/model.pth"

# SwanLab配置
swanlab:
  project_name: "training_framework"
  description: "深度学习训练实验"

# 数据配置
data:
  type: "cifar10"
  root: "./data"
  download: true
  augment: true
  num_workers: 4
  # 自定义数据集配置（当type为custom时使用）
  data_dir: "./data/raw/custom_dataset"
  csv_file: null
  image_size: 224
  train_split: 0.8

# GPU配置
gpu:
  device_ids: "2,3"
  auto_select: true

# 模型配置（网格搜索时由model_type参数动态设置）
model:
  type: null  # 将由网格搜索的model_type参数覆盖
  params: {}

# 损失函数配置
loss:
  type: "cross_entropy"
  params: {}

# 优化器配置
optimizer:
  type: "adam"
  params:
    weight_decay: 0

# 学习率调度器配置
scheduler:
  type: "onecycle"
  params:
    step_size: 10
    gamma: 0.1

# 网格搜索配置
grid_search:
  # 网格搜索参数定义
  grid:
    learning_rate: [0.001]
    batch_size: [256]
    dropout: [0.1]
    epochs: [3]
    model_type: ["resnet18", "resnet50", "efficientnet_b0"]
  
  # 网格搜索设置
  max_experiments: 50
  continue_on_error: true
  parallel_jobs: 1
  save_results: true
  results_file: "grid_search_results.csv"

# 多卡训练配置
multi_gpu:
  enabled: true
  strategy: "ddp"