# 任务配置
task:
  tag: "image_classification"
  description: "CIFAR-10图像分类任务"

# 训练配置
training:
  exp_name: "default_exp"
  save_model: true
  model_save_path: "models/model.pth"

# 实验记录 SwanLab配置
swanlab:
  project_name: "training_framework"
  description: "深度学习训练实验"

# 数据配置
data:
  type: "cifar10"
  root: "./data"
  download: true
  augment: true
  num_workers: 8
  # 自定义数据集配置（当type为custom时使用）
  data_dir: "./data/raw/custom_dataset"
  csv_file: null
  image_size: 224
  train_split: 0.8

# GPU配置
gpu:
  device_ids: "2,3"
  auto_select: true  # 未使用：当前代码中未实现自动GPU选择功能

# 多卡训练配置
multi_gpu:
  enabled: true  # 未使用：当前通过命令行参数--multi_gpu控制
  strategy: "ddp"  # 未使用：当前固定使用DDP策略

# 网格搜索设置
max_experiments: 50
continue_on_error: true  # 未使用：当前代码中未实现错误继续功能
parallel_jobs: 1  # 未使用：当前代码中未实现并行作业功能
save_results: true
results_file: "grid_search_results.csv"  # 未使用：文件名由时间戳自动生成

# 网格搜索超参数
grid_search:
  grid:
    # 模型相关参数
    model_name: ["resnet18", "resnet50", "efficientnet_b0"]
    
    # 超参数
    learning_rate: [0.001]
    batch_size: [512]
    dropout: [0.01]
    epochs: [3]
    
    # 损失函数
    loss: ["cross_entropy"]

    # 优化器参数
    optimizer_type: ["adam"]
    weight_decay: [0.0001]
    
    # 调度器参数
    scheduler_type: ["onecycle"]