# 训练配置
training:
  experiment_name: "default_exp"
  save_model: true
  model_save_path: "models/model.pth"

# 实验记录 SwanLab配置
swanlab:
  project_name: "training_framework"
  description: "深度学习训练实验"

# 数据配置
data:
  type: "cifar10"
  root: "./data"
  download: true
  augment: true
  num_workers: 8
  # 自定义数据集配置（当type为custom时使用）
  data_dir: "./data/raw/custom_dataset"
  csv_file: null
  image_size: 224
  train_split: 0.8

# GPU配置
gpu:
  device_ids: "2,3"
  auto_select: true

# 多卡训练配置
multi_gpu:
  enabled: true
  strategy: "ddp"  

# 网格搜索设置
max_experiments: 50
continue_on_error: true
parallel_jobs: 1
save_results: true
results_file: "grid_search_results.csv"

# 网格搜索超参数
grid_search:
  grid:
    # 模型相关参数
    model_name: ["resnet18", "resnet50", "efficientnet_b0"]
    
    # 超参数
    learning_rate: [0.001]
    batch_size: [512]
    dropout: [0.01]
    epochs: [3]
    
    # 损失函数
    loss: ["cross_entropy"]

    # 优化器参数
    optimizer_type: ["adam"]
    weight_decay: [0.0001]
    
    # 调度器参数
    scheduler_type: ["onecycle"]