# UCF-101视频分类配置文件
# 基于grid.yaml的视频分类任务配置

# 训练配置
training:
  experiment_name: "ucf101_baseline"
  save_model: true
  model_save_path: "models/video_model.pth"

# SwanLab配置
swanlab:
  project_name: "EasyTrain-Video"
  description: "UCF-101视频分类基线实验"

# 数据配置
data:
  type: "ucf101"
  root: "./data/UCF-101"
  annotation_path: "./data/ucfTrainTestlist"
  frames_per_clip: 16
  step_between_clips: 4
  fold: 1
  download: false
  augment: true
  num_workers: 8

# GPU配置
gpu:
  device_ids: "2,3"
  auto_select: true

# 多卡训练配置
multi_gpu:
  enabled: true
  strategy: "ddp"

# 超参数配置
hp:
  learning_rate: 0.001
  batch_size: 256  # 384
  epochs: 2
  weight_decay: 0.0001
  dropout: 0.2

# 模型配置
model:
  name: "r3d_18"
  params:
    pretrained: true
    num_classes: 101

# 损失函数配置
loss:
  name: "crossentropy"
  params:
    label_smoothing: 0.1

# 优化器配置
optimizer:
  name: "adamw"
  params:
    weight_decay: 0.0001
    betas: [0.9, 0.999]
    eps: 1e-8

# 学习率调度器配置
scheduler:
  name: "cosine"
  params:
    T_max: 10
    eta_min: 0.000001