# UCF-101视频分类网格搜索配置
# 用于搜索最佳的视频模型和超参数组合

# 训练配置
training:
  exp_name: "ucf101_grid_exp"
  save_model: true
  model_save_path: "models/video_model.pth"

# SwanLab配置
swanlab:
  project_name: "EasyTrain-Video-Grid"
  description: "UCF-101视频分类网格搜索实验"

# 数据配置
data:
  type: "ucf101"
  root: "./data/UCF-101"
  annotation_path: "./data/ucfTrainTestlist"
  download: false
  augment: true
  num_workers: 12
  fold: 1

# GPU配置
gpu:
  device_ids: "2,3"
  auto_select: true

# 多卡训练配置
multi_gpu:
  enabled: true
  strategy: "ddp"

# 网格搜索设置
max_experiments: 20
continue_on_error: true
parallel_jobs: 1
save_results: true
results_file: "video_grid_search_results.csv"

# 网格搜索超参数
grid_search:
  grid:
    # 模型相关参数
    model_name: ["mc3_18", "r3d_18", "r2plus1d_18"]
    
    # 超参数
    learning_rate: [0.001]
    batch_size: [384] # 256
    dropout: [0.01]
    epochs: [10]
    
    # 视频相关参数
    # frames_per_clip: [8]
    
    # 损失函数
    loss: ["crossentropy"]

    # 优化器参数
    optimizer_type: ["adam"]
    weight_decay: [0.0001]
    
    # 调度器参数
    scheduler_type: ["step", "cosine", "onecycle"]