# UCF-101视频分类配置文件
# 基于base.yaml的视频分类任务配置

# 超参数配置
hyperparameters:
  learning_rate: 0.001
  batch_size: 128  # 视频数据通常需要更小的batch size
  epochs: 2
  weight_decay: 0.0001

# 训练配置
training:
  save_model: true
  save_interval: 2
  log_interval: 10
  early_stopping:
    patience: 5
    min_delta: 0.001

# SwanLab配置
swanlab:
  project_name: "EasyTrain-Video"
  experiment_name: "ucf101_baseline"
  description: "UCF-101视频分类基线实验"
  tags: ["video", "ucf101", "action_recognition"]
  config:
    framework: "pytorch"
    task: "video_classification"

# 数据配置
data:
  type: "ucf101"
  root: "./data/UCF-101"
  annotation_path: "./data/ucfTrainTestlist"
  frames_per_clip: 16
  step_between_clips: 4
  fold: 1
  num_workers: 4
  pin_memory: true

# GPU配置
gpu:
  use_multi_gpu: true
  device_ids: "2,3"
  mixed_precision: true

# 模型配置
model:
  type: "r3d_18"
  params:
    pretrained: true
    num_classes: 101

# 损失函数配置
loss:
  type: "cross_entropy"
  params:
    label_smoothing: 0.1

# 优化器配置
optimizer:
  type: "adamw"
  params:
    weight_decay: 0.0001
    betas: [0.9, 0.999]
    eps: 1e-8

# 学习率调度器配置
scheduler:
  type: "cosine"
  params:
    T_max: 10
    eta_min: 1e-6